main: cz.Sicka.Core.Core
name: CreeplandsCore
version: 0.0.1-BETA_R0.0_DEV
author: Sicka_gp
softdepend: [Vault]
#softdepend: [Vault, Stats, mcMMO, GeoIPTools, Heroes, pvpstats, Factions, SimpleClans, ProtocolLib, HolographicDisplays, Autorank, Achievements]